### ISSUE TITLE
Reversed order of listing action logs

### ISSUE THREAD

**Issue by erik78se** [canonical/juju-dashboard#1033]
It makes alot more sense to reverse the order of the Action Log. (Tested on version 0.7.1)

Otherwise, a user would have to go to the bottom of the page all the time to find the last output.

![image](https://user-images.githubusercontent.com/850603/121095727-2a8f1d00-c7f1-11eb-82bd-c83d2c7e99ac.png)

**Comment by hatched** [comment]
Good idea! We're also going to be adding additional filtering mechanisms in coming releases which will also help when you have a model with a large number of actions being run over time.
