### ISSUE TITLE
Pressing the "Register a controller" button opens a popup that hides behind the sidebar

### ISSUE THREAD

**Issue by pazaan** [canonical/juju-dashboard#1643]
![Hidden Juju](https://github.com/canonical/juju-dashboard/assets/96943/31ec1703-8e9e-4e24-8769-b2b5504ced60)

macOS: 13.5.2 (22G91)
Safari: Version 16.6 (18615.3.12.11.2)
JAAS version: Version 0.11.2

**Comment by huwshimi** [comment]
Hi @pazaan thanks for that, I can reproduce this on the access and config panels as well.
