### ISSUE TITLE
Diagram for a large model doesn't fit into the dashboard

### ISSUE THREAD

**Issue by nobuto-m** [canonical/juju-dashboard#1706]
**To Reproduce**
1. Setup the dashboard as per https://juju.is/docs/juju/manage-the-juju-dashboard#heading--set-up-the-dashboard
2. Deploy a large model such as OpenStack https://charmhub.io/openstack-base
3. Open the dashboard and open the model in it

**Expected behavior**

The model should be shown nicely in the model diagram.

However, some apps are now shown in the preview rectangle.
![image](https://github.com/canonical/juju-dashboard/assets/4356209/fb5e1550-c080-4135-822e-19c322c3c9f2)

And when click the preview of the model diagram, it gets messy further.

![image](https://github.com/canonical/juju-dashboard/assets/4356209/cdc735e8-de25-458d-85c1-6ddcc4d61280)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser both Firefox and Chromium
 - Version Firefox 122, Chromium 121

**Comment by huwshimi** [comment]
Hi @nobuto-m these issues have been addressed in the latest release of the dashboard. We have not yet released updated charms with the fixes, but we plan to soon.

<img width="965" alt="Screenshot 2024-02-09 at 2 10 50 pm" src="https://github.com/canonical/juju-dashboard/assets/361637/f3d9a696-43cc-42aa-b204-390ea9909403">
<img width="1501" alt="Screenshot 2024-02-09 at 2 12 16 pm" src="https://github.com/canonical/juju-dashboard/assets/361637/d7e627e6-4619-4748-9270-1228da9b5b3b">

**Comment by huwshimi** [comment]
This fix was included in the [0.12.0](https://github.com/canonical/juju-dashboard/releases/tag/0.12.0) release.
