### ISSUE TITLE
Instance ID missing on GCE in machine table

### ISSUE THREAD

**Issue by hatched** [canonical/juju-dashboard#979]
Bootstrapped with Juju 2.9 and Dashboard 0.6.1 on GCE us-east

![Screen Shot 2021-04-28 at 10.12.21 AM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/f07f5395-dbca-46d5-863e-5cb3b858e19d)

**Comment by huwshimi** [comment]
This appears to be fixed now:

<img width="1509" alt="Screenshot 2023-09-06 at 10 24 22 am" src="https://github.com/canonical/juju-dashboard/assets/361637/4c5a6916-bb0e-477d-af7c-25710fbd41ad">
